[package]
name = "example-rust-c-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
extern-lib = { path = "../extern-lib" }
cubeos-service = { path = "../../../services/cubeos-service" }
juniper = "0.11"
log = "^0.4.0"