[package]
name = "isis-ants-service"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]
edition = "2018"

[features]
nos3 = ["isis-ants-api/nos3"]

[dependencies]
failure = "0.1.2"
isis-ants-api = { path = "../../apis/isis-ants-api" }
juniper =  "0.11"
cubeos-service = { path = "../cubeos-service" }
log = "^0.4.0"

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.10"
warp = "0.1.12"
