
[package]
name = "kubos-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
tokio = { version = "0.1" }
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false }
juniper = { version = "0.14.2" }
juniper_warp = { version = "0.5.2", default-features = false }
kubos-system = { path = "../../apis/system-api" }
log = { version = "^0.4.0", default-features = false }
warp = { version = "0.1.20", default-features = false }
# Pinning this to 0.3.15 due to kubos linux build issues with v0.3.16
pkg-config = {version = "= 0.3.15", default-features = false }

[dev-dependencies]
failure = "0.1.8"